#!/usr/bin/env bash
# setup.sh — register what to collect from this (sick) client machine.
#
# Super-simple CLI: asks which problem/working folder(s) to track, which log
# file(s) to tail, optionally a docs corpus dir and service names. Writes
# collect.conf next to this script, then (optionally) runs collector.sh to
# build the bundle + manifest immediately.
#
# Nothing here runs automatically on USB plug-in. The FDE copies this folder
# to the client laptop (or runs it straight off the stick) and invokes it.
#
# Interactive:      ./setup.sh
# Non-interactive:  ./setup.sh --problem-dir /path/to/problems \
#                              --log /var/log/backend.log --run

SETUP_VERSION="0.1.0"
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SCRIPT_DIR/collect.conf"

PROBLEM_DIRS=()
LOG_FILES=()
SERVICES=()
DOCS_DIR=""
LOG_TAIL_LINES=500
MAX_FILE_BYTES=5242880
RUN_AFTER=""   # "" = ask (interactive) / don't run (flag mode); yes/no via flags

usage() {
    cat <<'EOF'
Usage: setup.sh [options]

With no options, runs interactively.

  --problem-dir DIR   folder to register (repeatable) — the working folder of
                      problems, configs, broken app, etc.
  --log FILE          log file to track (repeatable)
  --docs-dir DIR      company-docs corpus directory (optional)
  --service NAME      systemd service to capture (repeatable, Linux only)
  --tail N            keep last N lines of each log (default 500)
  --run               run collector.sh immediately after writing config
  --no-run            write config only
  -h, --help          this help
EOF
}

abspath_dir() { (cd "$1" 2>/dev/null && pwd); }
abspath_file() {
    local d b
    d="$(dirname "$1")"; b="$(basename "$1")"
    d="$(cd "$d" 2>/dev/null && pwd)" || return 1
    printf '%s/%s' "$d" "$b"
}

INTERACTIVE=1
while [ $# -gt 0 ]; do
    INTERACTIVE=0
    case "$1" in
        --problem-dir) PROBLEM_DIRS+=("$2"); shift 2 ;;
        --log)         LOG_FILES+=("$2");   shift 2 ;;
        --docs-dir)    DOCS_DIR="$2";       shift 2 ;;
        --service)     SERVICES+=("$2");    shift 2 ;;
        --tail)        LOG_TAIL_LINES="$2"; shift 2 ;;
        --run)         RUN_AFTER=yes; shift ;;
        --no-run)      RUN_AFTER=no;  shift ;;
        -h|--help)     usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
    esac
done

echo "=============================================================="
echo " FDE War-Room Client Setup v$SETUP_VERSION"
echo " Registers what this machine will hand to the Brain."
echo "=============================================================="

if [ $INTERACTIVE -eq 1 ]; then
    echo
    echo "Which folder(s) hold the problem — the broken app, its configs,"
    echo "its working directory? (blank line to finish)"
    while :; do
        read -r -p "  problem folder path: " p
        [ -z "$p" ] && break
        if [ -d "$p" ]; then PROBLEM_DIRS+=("$p"); else echo "  !! not a directory, try again"; fi
    done

    echo
    echo "Which log file(s) should be tracked? (blank line to finish)"
    while :; do
        read -r -p "  log file path: " p
        [ -z "$p" ] && break
        if [ -f "$p" ]; then LOG_FILES+=("$p"); else echo "  !! not a file, try again"; fi
    done

    echo
    read -r -p "Company-docs corpus dir (optional, blank to skip): " DOCS_DIR

    echo
    echo "Systemd service names to capture, e.g. 'backend' (blank to finish):"
    while :; do
        read -r -p "  service name: " p
        [ -z "$p" ] && break
        SERVICES+=("$p")
    done
fi

if [ ${#PROBLEM_DIRS[@]} -eq 0 ] && [ ${#LOG_FILES[@]} -eq 0 ]; then
    echo "ERROR: nothing registered — need at least one problem folder or log file." >&2
    exit 1
fi

# Resolve everything to absolute paths so collector.sh works from any cwd.
RESOLVED_DIRS=()
for p in ${PROBLEM_DIRS[@]+"${PROBLEM_DIRS[@]}"}; do
    a="$(abspath_dir "$p")" || { echo "ERROR: cannot resolve dir: $p" >&2; exit 1; }
    RESOLVED_DIRS+=("$a")
done
RESOLVED_LOGS=()
for p in ${LOG_FILES[@]+"${LOG_FILES[@]}"}; do
    a="$(abspath_file "$p")" || { echo "ERROR: cannot resolve file: $p" >&2; exit 1; }
    [ -f "$a" ] || { echo "ERROR: log file not found: $p" >&2; exit 1; }
    RESOLVED_LOGS+=("$a")
done
if [ -n "$DOCS_DIR" ]; then
    DOCS_DIR="$(abspath_dir "$DOCS_DIR")" || { echo "ERROR: docs dir not found" >&2; exit 1; }
fi

# ------------------------------------------------------------ write conf ----

{
    echo "# collect.conf — generated by setup.sh v$SETUP_VERSION on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Edit by hand or re-run setup.sh to regenerate."
    printf 'PROBLEM_DIRS=('
    for p in ${RESOLVED_DIRS[@]+"${RESOLVED_DIRS[@]}"}; do printf '%q ' "$p"; done
    printf ')\n'
    printf 'LOG_FILES=('
    for p in ${RESOLVED_LOGS[@]+"${RESOLVED_LOGS[@]}"}; do printf '%q ' "$p"; done
    printf ')\n'
    printf 'SERVICES=('
    for p in ${SERVICES[@]+"${SERVICES[@]}"}; do printf '%q ' "$p"; done
    printf ')\n'
    printf 'DOCS_DIR=%q\n' "$DOCS_DIR"
    printf 'LOG_TAIL_LINES=%q\n' "$LOG_TAIL_LINES"
    printf 'MAX_FILE_BYTES=%q\n' "$MAX_FILE_BYTES"
} > "$CONF"

echo
echo "Registered targets written to: $CONF"
echo "  problem folders: ${#RESOLVED_DIRS[@]}"
echo "  log files:       ${#RESOLVED_LOGS[@]}"
echo "  services:        ${#SERVICES[@]}"
echo "  docs corpus:     ${DOCS_DIR:-<none>}"

# ------------------------------------------------------------ run collector -

if [ -z "$RUN_AFTER" ] && [ $INTERACTIVE -eq 1 ]; then
    echo
    read -r -p "Run collection now and build the bundle + manifest? [Y/n] " ans
    case "${ans:-Y}" in [Yy]*) RUN_AFTER=yes ;; *) RUN_AFTER=no ;; esac
fi

if [ "$RUN_AFTER" = "yes" ]; then
    echo
    exec bash "$SCRIPT_DIR/collector.sh" --conf "$CONF"
else
    echo
    echo "Config saved. Build the bundle any time with:  ./collector.sh"
fi
